general:
  experiment: "loclic"
  main_path: "YourMainPath"
  dataset: "PathToDataset"
  config: "loclic"
train:
  dataset_csv: "train_256"
  seed: 192
  epochs: 100
  learning_rate: 0.0001
  num_workers: 16
  lmbda: 0.01
  lmbda2: 1
  batch_size: 2
  test_batch_size: 2
  aux_learning_rate: 0.001
  patch_size: [256, 256] # [512, 512]
  cuda: True
  save: True
  clip_max_norm: 1.0
  checkpoint: None
  world_size: 1
  dist_url: "env://"
  dist_backend: "nccl"
  save_every: 1
test: 
  test_dataset: "YourTestDataset"
  batch_size: 1
  checkpoint: "YourCheckpoint"
  output_dir: "YourOutputDir"
  lmbda: 0.01 # To calculate the loss
  lmbda2: 1 # To calculate the loss
